--
--	Created by: AnkhoD
--	Created on: 03/20/14 12:58:35
--
--	Copyright (c) 2014 MyCompanyName
--	All Rights Reserved
--

if main_choice is "Play From" then			if no_bookmarks is 0 then				display dialog "No bookmarks have been set." buttons {"OK"} default button 1				return			end if			set choice to (choose from list choosefrom_list ¬				with prompt ¬				"Play from which bookmark?" OK button name ¬				"Play" without multiple selections allowed)			if choice is false then				return "User decided not to"			end if			set choice to the first item of choice			repeat with n from 1 to (count of bookmark_list)				if choice is equal to (item n of bookmark_list) then					set unique_id to item (n + 1) of bookmark_list					set seconds_in to item (n + 2) of bookmark_list					set unique_id to unique_id as number					set seconds_in to seconds_in as number				end if			end repeat						tell source "Library"				tell playlist "Library"					--					-- We are forbidden to say"the track whose database ID is X" as there					-- may be multiple copies of the same MP3 file in the database,					-- i.e., database IDs are not (as the dictionary implies) unique;					-- instead"every track whose database ID is X" successfully					-- produces a list of size 1, containing the answer.					--					set inefficient to (every track whose database ID is unique_id)					repeat with i in inefficient						-- display dialog (name of i as string) buttons {"OK"} default button 1						set track_in_question to i					end repeat				end tell			end tell						-- Finally instruct iTunes to act						-- stop			play track_in_question			set jump_to_position to seconds_in		end if			on error error_message number error_number		if the error_number is not -128 then			beep			display dialog error_message buttons {"OK"} default button 1		end if	end tryend tell-- A variety of baffling behaviours result from attempting to-- set the player position in the same tell as the play command,-- once the script is compiled (it works fine if run from the editor);-- hence this clumsy second tell. Presumably another iTunes bug.----tell application "iTunes"--	activate--	if jump_to_position ≥ 0 then--		set the player position to jump_to_position--	end if--end tellon access_website(this_URL)	ignoring application responses		tell application "Finder"			open location this_URL		end tell	end ignoringend access_website
