/*!
	@header
	@copyright 2012 Apple Inc.
 */

#import <iTunesLibrary/ITLibMediaEntity.h>
#import <iTunesLibrary/ITLibDefines.h>

/*!
	@enum		ITLibDistinguishedPlaylistKind
    @abstract	These constants specify the possible kinds of playlists.
 
	@constant	ITLibDistinguishedPlaylistKindNone
				The playlist is not a distinguished playlist.
	@constant	ITLibDistinguishedPlaylistKindMovies
				The playlist contains all the movies in the iTunes Library.
	@constant	ITLibDistinguishedPlaylistKindTVShows
				The playlists contains all the TV shows in the iTunes Library.
	@constant	ITLibDistinguishedPlaylistKindMusic
				The playlist contains all the music items in the iTunes Library.
	@constant	ITLibDistinguishedPlaylistKindBooks
				The playlist contains all the books in the iTunes Library
	@constant	ITLibDistinguishedPlaylistKindRingtones
				The playlist contains all the ringtones in the iTunes Library.
	@constant	ITLibDistinguishedPlaylistKindPodcasts
				The playlist contains all the podcasts in the iTunes library
	@constant	ITLibDistinguishedPlaylistKindVoiceMemos
				The playlist contains all voice memos.
	@constant	ITLibDistinguishedPlaylistKindApplications
				The playlist contains all the iOS applications of the user in iTunes.
	@constant	ITLibDistinguishedPlaylistKindPurchases
				The playlist contains all the user's purchases in the iTunes Store.
	@constant	ITLibDistinguishedPlaylistKindiTunesU
				The playlist contains the user's iTunesU items.
	@constant	ITLibDistinguishedPlaylistKind90sMusic
				The playlist is the default 90's music iTunes playlist.
	@constant	ITLibDistinguishedPlaylistKindMyTopRated
				The playlist is the default Top Rated smart playlist generated by iTunes.
	@constant	ITLibDistinguishedPlaylistKindTop25MostPlayed
				The playlist is the default 25 Most Played smart playlist generated by iTunes.
	@constant	ITLibDistinguishedPlaylistKindRecentlyPlayed
				The playlist is the default Recently Played smart playlist generated by iTunes .
	@constant	ITLibDistinguishedPlaylistKindRecentlyAdded
				The playlist is the default Recently Added smart playlist generated by iTunes.
	@constant	ITLibDistinguishedPlaylistKindMusicVideos
				The playlist is the default Music Videos smart playlist generated by iTunes.
	@constant	ITLibDistinguishedPlaylistKindClassicalMusic
				The playlist is the default Classical Music smart playlist generated by iTunes.
	@constant	ITLibDistinguishedPlaylistKindLibraryMusicVideos
				The playlist contains all music videos in the iTunes Library. This is NOT the same as the default Music Videos smart playlist.
	@constant	ITLibDistinguishedPlaylistKindLibraryHomeVideos
				The playlist contains all homes videos in the iTunes Library.
*/
enum
{
	ITLibDistinguishedPlaylistKindNone = 0,
	ITLibDistinguishedPlaylistKindMovies = 1,
	ITLibDistinguishedPlaylistKindTVShows = 2,
	ITLibDistinguishedPlaylistKindMusic = 3,
	ITLibDistinguishedPlaylistKindBooks = 4,
	ITLibDistinguishedPlaylistKindRingtones = 5,
	ITLibDistinguishedPlaylistKindPodcasts = 7,
	ITLibDistinguishedPlaylistKindVoiceMemos = 14,
	ITLibDistinguishedPlaylistKindPurchases = 16,
	ITLibDistinguishedPlaylistKindiTunesU = 26,
	ITLibDistinguishedPlaylistKind90sMusic = 42,
	ITLibDistinguishedPlaylistKindMyTopRated = 43,
	ITLibDistinguishedPlaylistKindTop25MostPlayed = 44,
	ITLibDistinguishedPlaylistKindRecentlyPlayed = 45,
	ITLibDistinguishedPlaylistKindRecentlyAdded = 46,
	ITLibDistinguishedPlaylistKindMusicVideos = 47,
	ITLibDistinguishedPlaylistKindClassicalMusic = 48,
	ITLibDistinguishedPlaylistKindLibraryMusicVideos = 49,
	ITLibDistinguishedPlaylistKindHomeVideos = 50,
};

typedef NSUInteger ITLibDistinguishedPlaylistKind;

/*!
 @abstract	A playlist is a collection of related media items. (Media items are described in ITLibMediaItem Class Reference.) 
			Each playlist has a name, a set of attributes, and a unique identifier that persists across application launches.
*/
ITLIB_EXPORT @interface ITLibPlaylist : ITLibMediaEntity
{
	NSMutableArray * _items;
}

/*! @abstract The name or title of this playlist. */
@property (readonly, nonatomic, copy) NSString* name;

/*! @abstract Whether this playlist is a master playlist. */
@property (readonly, nonatomic, assign, getter=isMaster) BOOL master;

/*! @abstract The unique identifier of this playlist' parent. */
@property (readonly, nonatomic, retain) NSNumber* parentID;

/*! @abstract Whether this playlist is visible. */
@property (readonly, nonatomic, assign, getter=isVisible) BOOL visible;

/*! 
 * @abstract Whether this playlist is an "all items" playlist (i.e. marked items 
 * in playlist exceeds the total tracks in the playlist so the 
 * playlist is a discreet object). 
 */
@property (readonly, nonatomic, assign, getter=isAllItemsPlaylist) BOOL allItemsPlaylist;

/*! @abstract The media items contained within this playlist. */
@property (readonly, nonatomic, retain) NSArray* items;

/*! @abstract The distinguished kind of this playlist. */
@property (readonly, nonatomic, assign) ITLibDistinguishedPlaylistKind distinguishedKind;

@end

/*! 
 * @constant ITLibPlaylistPropertyName.
 * @abstract Retrieves the name or title of the playlist. See @link name @/link.
 */
ITLIB_EXPORT ITLIB_EXTERN NSString * const ITLibPlaylistPropertyName;

/*! @constant ITLibPlaylistPropertyAllItems. See allItemsPlaylist. */
ITLIB_EXPORT ITLIB_EXTERN NSString * const ITLibPlaylistPropertyAllItemsPlaylist;

/*! @constant ITLibPlaylistPropertyDistinguisedKind. See*/
ITLIB_EXPORT ITLIB_EXTERN NSString * const ITLibPlaylistPropertyDistinguisedKind;

/*! @constant ITLibPlaylistPropertyMaster. */
ITLIB_EXPORT ITLIB_EXTERN NSString * const ITLibPlaylistPropertyMaster;

/*! @constant ITLibPlaylistPropertyParentPersistentID. */
ITLIB_EXPORT ITLIB_EXTERN NSString * const ITLibPlaylistPropertyParentPersistentID;

/*! @constant ITLibPlaylistPropertyVisible. */
ITLIB_EXPORT ITLIB_EXTERN NSString * const ITLibPlaylistPropertyVisible;

/*! @constant ITLibPlaylistPropertyItems. */
ITLIB_EXPORT ITLIB_EXTERN NSString * const ITLibPlaylistPropertyItems;
